version: '2'
services:
    jhipster-app:
        image: jhipster
        external_links:
            - jhipster-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    jhipster-mysql:
        extends:
            file: mysql.yml
            service: jhipster-mysql
